services:
    problematic_ip_hunter.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine
        factory_method: getEntityManager
        arguments: [%problematic_ip_hunter.model_manager_name%]
        public: false
    problematic_ip_hunter.event_listener.request:
        class: Problematic\IPHunterBundle\EventListener\RequestListener
        arguments:
            securityContext: "@security.context"
            logManager: "@problematic_ip_hunter.manager.log"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelRequest, priority: -1024 }
    problematic_ip_hunter.manager.log:
        class: Problematic\IPHunterBundle\Entity\HunterLogManager
        arguments:
            em: "@problematic_ip_hunter.entity_manager"
            class: %problematic_ip_hunter.model.log.class%
